// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using projectC.model;

namespace projectC.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20181112113359_sandwich")]
    partial class sandwich
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("projectC.model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("projectC.model.Favourite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("favourites");
                });

            modelBuilder.Entity("projectC.model.ImageURL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("url");

                    b.HasKey("Id");

                    b.ToTable("ImageURL");
                });

            modelBuilder.Entity("projectC.model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<int>("ImageURL");

                    b.Property<string>("Name");

                    b.Property<float>("Price");

                    b.Property<int?>("imageURLId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("imageURLId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("projectC.model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("projectC.model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("LastName");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("projectC.model.Favourite", b =>
                {
                    b.HasOne("projectC.model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("projectC.model.Product", b =>
                {
                    b.HasOne("projectC.model.Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.HasOne("projectC.model.ImageURL", "imageURL")
                        .WithMany("products")
                        .HasForeignKey("imageURLId");
                });

            modelBuilder.Entity("projectC.model.User", b =>
                {
                    b.HasOne("projectC.model.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
